### ISSUE TITLE
Filetype exclude not work

### ISSUE THREAD

**Issue by tin-pham** [zakharykaplan/nvim-retrail#4]
My config 
```lua
require("retrail").setup({
  -- Enabled filetypes.
  filetype = {
    -- Strictly enable only on `include`ed filetypes. When false, only disabled
    -- on an `exclude`ed filetype.
    strict = false,
    -- Included filetype list.
    include = {},
    -- Excluded filetype list. Overrides `include` list.
    exclude = {
      'help', 'startify', 'dashboard', 'packer', 'neogitstatus', 'nvimtree', 'trouble', 'alpha',
      'lir', 'Outline', 'spectre_panel', 'toggleterm', 'qf'
    }
  }
})
```

Dashboard still have highlight
![image](https://user-images.githubusercontent.com/20679090/180893840-d48c0278-5833-4088-90c6-d4c418117e31.png)

Filetype is 'dashboard'
![image](https://user-images.githubusercontent.com/20679090/180893885-73826281-4fc7-4167-87f8-97a89e663cd9.png)

But when i do something like toggle the neo-tree, or close the lspinfo banner in the image above, it goes back to normal 
![image](https://user-images.githubusercontent.com/20679090/180893963-640925e6-2712-407d-8a44-950480531073.png)

Edit: I discover more, if the dashboard no longer have highlight, then it will "toggle" to my tree
![image](https://user-images.githubusercontent.com/20679090/180894232-83cf4531-25d9-4014-a663-6b144f51327a.png)

Initial state
![image](https://user-images.githubusercontent.com/20679090/180894429-2ae83d0f-2487-4de2-98e8-5b610c4f6b2a.png)

**Comment by kaplanz** [comment]
Hm ok, this is a sneaky bug.

It seems this is happening due your config not explicitly excluding `""`. Because of this, when Neovim launches (*before* the filetype is set to `dashboard`) the plugin checks and sees that `""` isn't excluded and decides to enable itself on that window. This actually explains the behaviour you're seeing with nvim-tree as well.

This is actually a regression from 6dd0fe7, where I removed the `FileType` autocommand firing a refresh. For now as a quick fix add `""` as an excluded filetype. The obvious patch here is to re-introduce the `FileType` trigger, but this may have unintended consequences regarding issue #2, so further testing is required before I can push that.

**Comment by kaplanz** [comment]
Fixed. Let me know if the problem persists for you, otherwise please close this issue.

I believe issues #2, #3 should not be affected by this, but if you're getting the `E803` error please comment on issue #3.

**Comment by tin-pham** [comment]
Thanks the dashboard now fixed but what about this, i try to exclude 'neo-tree' and got this when i open neo-tree
![image](https://user-images.githubusercontent.com/20679090/180924345-9e4e0b26-fbb0-4cf5-92de-b3a3cbb92287.png)

**Comment by tin-pham** [comment]
And also I don't if it relate, but I saw the 'retrail' in the error, when I navigate between neotree and dashboard
![image](https://user-images.githubusercontent.com/20679090/180926615-62f64079-97cd-44b2-ad74-07b3519774f9.png)

And if I open with dashboard, it will have the trailing highlight on neo-tree, if I open a file, it not, and navigate around normally 

![image](https://user-images.githubusercontent.com/20679090/180926709-7498d591-5c93-4aa8-8f52-c42f8124992b.png)

**Comment by kaplanz** [comment]
This should be fixed as well now. See #3.

Closing this issue since it was solved in bb30f21.

**Comment by tin-pham** [comment]
![image](https://user-images.githubusercontent.com/20679090/181012034-359e11b1-f456-4ce6-af53-875637a02a05.png)
It still happen to me when i switch buffer, I update to the last commit
